### ISSUE TITLE
Explore DGS

### ISSUE THREAD

**Issue by fjlopez** [IAAA-Lab/space-ql#10]
DGS is a production-ready Netflix framework for building GraphQL servers quickly. It can boost your work!

https://netflix.github.io/dgs/

**Comment by alecron** [comment]
- [ ] Make the [Getting started tutorial](https://netflix.github.io/dgs/getting-started/)

**Comment by alecron** [comment]
I like what Apollo brings to React but i think the tutorial could be better structured. Anyway, I'll make the tutorial with kotlin-react to see how it would look like.
