### ISSUE TITLE
Add suggestions to searchbar

### ISSUE THREAD

**Issue by alecron** [IAAA-Lab/space-ql#27]

**Comment by alecron** [comment]
There are some errors to fix. It doesn't always work as expected, Elasticsearch doesn't return the results properly if the whole title is set as input

**Comment by fjlopez** [comment]
Can your add an example? Which is the expected outcome? I recommend to add and use a template like https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md Review https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository to enable support by GitHub.

**Comment by fjlopez** [comment]
Done, you have now templates and can be updated to your preferred format.
