### ISSUE TITLE
Config4k not working on KotlinJS

### ISSUE THREAD

**Issue by alecron** [IAAA-Lab/space-ql#31]
The library [Config4k](https://github.com/config4k/config4k), which is supposed to be a [Lightbend Config](https://github.com/lightbend/config)'s wrapper for kotlin, is not being found by IntelliJ when trying to import the package from jsMain. On the other hand, it does work when the package is imported from the jvmMain, so it seems like it isn't compatible with KotlinJS.

**Comment by fjlopez** [comment]
Why do you need `config4k` in the client side of the app? You can process HOCON in the server side of the app with `config4k` and then expose the configuration objects through an API in JSON using kotlinx.serialization.

**Comment by alecron** [comment]
We talked about using HOCON and `Config4k` because I had some parts where i had "localhost:8000" hardcoded in `API.kt`. As i understood it, i had to use a HOCON config file to save this route to the graphql endpoint that appears in the  API file. I don't get how or why to expose an API to the client. I thought that, in this case, using HOCON was about creating constants/properties that were easily accessible to avoid hardcoding them.

**Comment by fjlopez** [comment]
Have you tested the use of a relative location, i.e.:

```
server {
    graphql = "graphql"
} 
```

In addition you can use `Location` from `kotlin-stdlib` to discover this information. See https://kotlinlang.org/api/latest/jvm/stdlib/org.w3c.dom/-location/
