### ISSUE TITLE
Can't find the JS generated

### ISSUE THREAD

**Issue by alecron** [IAAA-Lab/space-ql#4]
When i try to run the app it seems to run but the html doesn seem to find the .js generated. I've tried multiple locations such us /resources/space-ql or /static/space-ql or just space-ql but nothing happens. 
I've also tried to change the gradle build script to make it look like **[this](https://github.com/kotlin-hands-on/jvm-js-fullstack/blob/final/build.gradle.kts)** (trying to configure the tasks as they appear there to put the JS into every jar) but it only creates more warnings/errors.
The last thing i've tried is to  create a CommonMain folder with a resources folder on it containing the Html. I thought that maybe that way both the html and the js are accessible for every part of the app and so it could find the js from the html, but i doesn't work either.

**Comment by fjlopez** [comment]
Now it should work in any environment. The change is from: 

https://github.com/IAAA-Lab/space-ql/blob/2f00a84cbda2c4332cd6bf12eaacfbf45c5417f1/build.gradle.kts#L27-L35

to:

https://github.com/IAAA-Lab/space-ql/blob/62adca08b0c50422f1d217b0e76976ac7020b5d8/build.gradle.kts#L27-L35


The instruction `binaries.executable()` explicitly instructs the Kotlin compiler to emit executable `.js` files. However, in multiplatform projects this instruction must be within a target (`browser`) . It should be a bug in macos that it worked outside a target.

**Comment by alecron** [comment]
It works perfectly. Thanks
